### ISSUE TITLE
TypeError: request.body.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by PHILLIPS71** [diegohaz/generator-rest#5] opened 2016-09-23 08:44 UTC
When I attempt to make a post request to one of my own api endpoint that I have generated, I'm continuing to get this below response. I think I'm using the API correctly I've followed along with the documentation a few times and it continues to occur.  

`TypeError: request.body.hasOwnProperty is not a function
    at JwtStrategy.<anonymous> (/Users/~/Documents/Development/Websites/servers-rest/node_modules/passport-jwt/lib/extract_jwt.js:30:42)
    at JwtStrategy._jwtFromRequest (/Users/~/Documents/Development/Websites/servers-rest/node_modules/passport-jwt/lib/extract_jwt.js:82:39)
    at JwtStrategy.authenticate (/Users/~/Documents/Development/Websites/servers-rest/node_modules/passport-jwt/lib/strategy.js:84:22)
    at attempt (/Users/~/Documents/Development/Websites/servers-rest/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/Users/~/Documents/Development/Websites/servers-rest/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at /Users/~/Documents/Development/Websites/servers-rest/src/services/passport/index.js:26:3
    at Layer.handle [as handle_request] (/Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/layer.js:95:5)
    at /Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/index.js:312:13)
    at /Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/~/Documents/Development/Websites/servers-rest/node_modules/express/lib/router/index.js:46:12)
`

**Comment by diegohaz** [comment] 2016-09-23 08:58
How are you calling the API? It seems like you aren't passing an object to `request.body`.

**Comment by PHILLIPS71** [comment] 2016-09-23 09:03
At the moment I'm testing around with it in Postman, where I have set the body objects in there.

**Comment by diegohaz** [comment] 2016-09-23 09:08
Does it happen on a clean install?

Can you create a repository with your code so I can use it to reproduce the problem?

**Comment by PHILLIPS71** [comment] 2016-09-23 09:32
I tried a clan install and it was still occurring, here is a repo with my current code: https://github.com/PHILLIPS71/generator-rest

**Comment by diegohaz** [comment] 2016-09-23 09:51
I can't reproduce your problem. It works perfectly here:
![image](https://cloud.githubusercontent.com/assets/3068563/18781799/b7973a90-8159-11e6-9f94-666d536fd74b.png)

Maybe the node version (`node -v`)?
Or remove the node_modules path, clean the npm cache (`npm cache clean`), and npm install again, if you didn't try this yet.

**Comment by PHILLIPS71** [comment] 2016-09-23 10:12
I've tried cleaning the cache and reinstalling all the node modules, but still getting the error. The version of node I'm using is v6.5.0 and npm v3.10.3

**Comment by diegohaz** [comment] 2016-09-23 10:30
The generated code is tested on node v6 with different endpoint structures and everything is going fine: https://travis-ci.org/diegohaz/generator-rest/jobs/161886181

You can run `npm test` and see if it throws.

If nothing changes, start debugging the code to find where exactly this error occurs (e.g. `console.log(request.body)` on `/Users/~/Documents/Development/Websites/servers-rest/node_modules/passport-jwt/lib/extract_jwt.js:30:42` and so on)

**Comment by diegohaz** [comment] 2016-10-02 12:51
Closing due to inactivity. If anyone else can reproduce this issue, please tell me and I will reopen it.

**Comment by aluengo** [comment] 2016-10-11 12:59
Hello,

I've got exactly the same problem...I'm following the steps as described in the video:
1. I've created (signed up) a user >> OK
2. I've logged in a user in order to get a token >> OK
3. When I try to create a new article I get the same error `TypeError: request.body.hasOwnProperty is not a function`

I think is a problem with authentication, since error is happening at that point: /src/services/passport/index.js:26:3

I have tried to clean up everything and execute `npm install` again with no success.

My node version is **v6.7.0** and npm **3.10.3**

**Comment by diegohaz** [comment] 2016-10-11 13:16
Hi, @aluengo.

Could you run `npm test` and see if it throws any errors?

**Comment by aluengo** [comment] 2016-10-11 13:33
Apparently seems to be OK.

![screen_shot](https://cloud.githubusercontent.com/assets/475431/19272070/775a899c-8fc7-11e6-962f-4635ca47af5e.png)

I thought it might be related with this issue [https://github.com/themikenicholson/passport-jwt/pull/77](url)

I'm new to Node, but I've checked in `node_modules/passport-jwt/lib/extract_jwt.js` and I've seen that for `extractors.fromBodyField[...]` it was the old code `request.body.hasOwnProperty(field_name)` I've changed it manually to the new one `Object.prototype.hasOwnProperty.call(request.body, field_name)`, restarted the server and now it works OK.

I guess I should update the `package.json` to use a newer version of extract_jwt.js and issue solved...

**Comment by diegohaz** [comment] 2016-10-11 13:44
Hmmm, I need to see why this wasn't caught by tests.

As stated in https://github.com/themikenicholson/passport-jwt/pull/77 this issue is solved with querystrings.

Can you back to the state where the problem occurs and send the access_token through querystring instead? `POST /articles?access_token=token`

If it works, this probably will be a better solution as we don't have control over `passport-jwt` dependencies.

**Comment by aluengo** [comment] 2016-10-11 13:58
I've rollbacked changes, tested again as usual and failed. Then, as you suggested, I've tried sending access_token as a parameter (keeping title and content in the body) and it worked perfectly!

**Comment by diegohaz** [comment] 2016-10-11 14:10
Nice. :)
I'll update package.json when they solve the issue in `passport-jwt`.

But it's strange that the tests didn't catch this, even having tests sending `acess_token` through `request.body`. 😭

**Closed by diegohaz** 2016-10-11 14:10 UTC
Labels: bug
